//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace AssemblyCSharp
{
		public class BaseMap
		{
				String className = "no name";

				public BaseMap (String name)
				{
						this.className = name;
						Console.Out.WriteLine (className);
				}

				public void GetName ()
				{

		
			Debug.Log ("das");

						
			
				}

		}

}

